### ISSUE TITLE
First Version Works Great!

### ISSUE THREAD

**Issue by vinkla** [volkert/forecast-player#8]
Just wanted to say that this is a great idea. Keep up the good work! What have you planned for the future? New features?

**Comment by volkert** [comment]
Thanks! There is no real roadmap yet. Some features are written down as issues. But there are no bigger plans. Is there anything you would like to see?

**Comment by vinkla** [comment]
As I've understood, this show the list of favorites? Maybe we could add the news feed as well? That could be a great feature. The best thing about the app is using Soundcloud with Mac's media keys IMO.

**Comment by volkert** [comment]
That is actually the first issue #1 I created :)
I hope I'll find the time to implement this soon.

**Comment by vinkla** [comment]
Yeah, that would be great!
